// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkshopXamarinFormsApi.DataContext;

namespace WorkshopXamarinFormsApi.Migrations
{
    [DbContext(typeof(BranchesContext))]
    [Migration("20211105112530_DataMigration")]
    partial class DataMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("WorkshopXamarinForms.DataContext.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.HasKey("BranchId");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            BranchId = 1,
                            Location = "Av. Paseo de la Reforma 483, Cuauhtémoc, 06500 Ciudad de México, CDMX ",
                            Name = "Reforma"
                        },
                        new
                        {
                            BranchId = 2,
                            Location = "Calz. Vallejo 1090, Sta Cruz de las Salinas, Azcapotzalco, 02300 Ciudad de México, CDMX ",
                            Name = "Vallejo"
                        },
                        new
                        {
                            BranchId = 3,
                            Location = "Av. Central Alta Tensión Del, Alfonso XIII, 01460 Ciudad de México ",
                            Name = "AV. Central"
                        },
                        new
                        {
                            BranchId = 4,
                            Location = "Atlixcáyotl 2501, Reserva Territorial Atlixcáyotl, 72830 Puebla, Pue. ",
                            Name = "Puebla"
                        },
                        new
                        {
                            BranchId = 5,
                            Location = "Prol Corregidora Sur # 3, Centro, 76000 Santiago de Querétaro, Qro. ",
                            Name = "Querétaro"
                        },
                        new
                        {
                            BranchId = 6,
                            Location = "Matucana 501, Santiago, Región Metropolitana, Chile ",
                            Name = "Santiago de Chile"
                        },
                        new
                        {
                            BranchId = 7,
                            Location = "Av. Mcal. López 3350, Asunción, Paraguay",
                            Name = "Asunción"
                        },
                        new
                        {
                            BranchId = 8,
                            Location = "PEDRO PARGA  , ZONA CENTRO , 20000 Aguascalientes. México ",
                            Name = "AGUASCALIENTES"
                        },
                        new
                        {
                            BranchId = 9,
                            Location = "PEDRO PARGA  231, ZONA CENTRO , 20000 Aguascalientes. México ",
                            Name = "AGUASCALIENTES"
                        },
                        new
                        {
                            BranchId = 10,
                            Location = "ZARAGOZA  212 BIS, CENTRO, 20800 Aguascalientes. México ",
                            Name = "CALVILLO"
                        },
                        new
                        {
                            BranchId = 11,
                            Location = "MIGUEL RUELAS  108, MIRAVALLE, 20400 Aguascalientes. México ",
                            Name = "COLONIA MIRAVALLE DE AGUASCALIENTES"
                        },
                        new
                        {
                            BranchId = 12,
                            Location = "JUÁREZ  23, CENTRO, 20460 Aguascalientes. México ",
                            Name = "COSÍO"
                        },
                        new
                        {
                            BranchId = 13,
                            Location = "ARAGÓN  103-B, FRACCIONAMIENTO ESPAÑA, 20210 Aguascalientes. México ",
                            Name = "FRACCIONAMIENTO ESPAÑA DE AGUASCALIENTES"
                        },
                        new
                        {
                            BranchId = 14,
                            Location = "JULIO DÍAZ TORRE 110, CIUDAD INDUSTRIAL, 20290 Aguascalientes. México ",
                            Name = "CENTRO S.C.T. AGUASCALIENTES"
                        },
                        new
                        {
                            BranchId = 15,
                            Location = "EMILIO RANGEL  201, CENTRO, 20320 Aguascalientes. México ",
                            Name = "JOSE MARÍA MORELOS Y PAVON"
                        },
                        new
                        {
                            BranchId = 16,
                            Location = "PINO SUÁREZ 18, CENTRO, 20670 Aguascalientes. México ",
                            Name = "PABELLÓN DE ARTEAGA"
                        },
                        new
                        {
                            BranchId = 17,
                            Location = "PRIMO VERDAD  101, CENTRO, 20400 Aguascalientes. México ",
                            Name = "RINCÓN DE ROMOS"
                        },
                        new
                        {
                            BranchId = 18,
                            Location = "REPÚBLICA DE BRASIL  608, FRACCIONAMIENTO JARDINES DE SANTA ELENA, 20236 Aguascalientes. México ",
                            Name = "CENTRAL CAMIONERA DE AGUASCALIENTES"
                        },
                        new
                        {
                            BranchId = 19,
                            Location = "SAN MIGUEL  202, CENTRO, 20900 Aguascalientes. México ",
                            Name = "JESÚS MARÍA"
                        },
                        new
                        {
                            BranchId = 23,
                            Location = "PLAZA JUÁREZ  110, CENTRO, 20710 Aguascalientes. México ",
                            Name = "ASIENTOS"
                        },
                        new
                        {
                            BranchId = 24,
                            Location = "AV. JESÚS MACIAS RANGEL  120 PTE., CENTRO, 20700 Aguascalientes. México ",
                            Name = "VILLA JUÁREZ"
                        },
                        new
                        {
                            BranchId = 25,
                            Location = "JUAN  DOMINGUEZ  101, SAN JOSÉ DE GRACIA CENTRO , 20500 Aguascalientes. México ",
                            Name = "SAN JOSÉ DE GRACIA"
                        },
                        new
                        {
                            BranchId = 26,
                            Location = "AV. DE LOS MAESTROS  102, INSURGENTES, 20287 Aguascalientes. México ",
                            Name = "DELEGACIÓN INSURGENTES  DE AGUASCALIENTES"
                        },
                        new
                        {
                            BranchId = 27,
                            Location = "PLAZA JUÁREZ  4, ZONA CENTRO, 20600 Aguascalientes. México ",
                            Name = "TEPEZALÁ"
                        },
                        new
                        {
                            BranchId = 29,
                            Location = "AV. ESTADO 29  24, CENTRO, 22910 Baja California. México ",
                            Name = "CAMALÚ"
                        },
                        new
                        {
                            BranchId = 30,
                            Location = "JOSÉ MARÍA MORELOS Y PAVÓN 521, ZONA CENTRO, 21960 Baja California. México ",
                            Name = "CIUDAD MORELOS"
                        },
                        new
                        {
                            BranchId = 31,
                            Location = "BAHÍA DE LOS ÁNGELES S/N, BAJA CALIFORNIA, 21130 Baja California. México ",
                            Name = "COLONIA BAJA CALIFORNIA DE MEXICALI"
                        },
                        new
                        {
                            BranchId = 32,
                            Location = "CALLE CORTES  1983, HIDALGO, 22880 Baja California. México ",
                            Name = "COLONIA HIDALGO DE ENSENADA"
                        },
                        new
                        {
                            BranchId = 33,
                            Location = "CALZ. INDEPENDENCIA  S/N, INDEPENDENCIA, 21290 Baja California. México ",
                            Name = "COLONIA INDEPENDENCIA DE MEXICALI"
                        },
                        new
                        {
                            BranchId = 34,
                            Location = "BLVD. DÍAZ ORDAZ,  CENTRO COMERCIAL 5 Y 10 14517, LAS FUENTES, 22115 Baja California. México ",
                            Name = "COLONIA LAS BRISAS DE TIJUANA"
                        },
                        new
                        {
                            BranchId = 35,
                            Location = "CARRETERA TRANSPENINSULAR KM 195 , EJIDO NUEVO BAJA CALIFORNIA, 22930 Baja California. México ",
                            Name = "COLONIA LÁZARO CÁRDENAS DEL VALLE DE SAN QUINTÍN"
                        },
                        new
                        {
                            BranchId = 36,
                            Location = "BAHIA DE KINO S/N, LOMAS DEL PORVENIR, 22535 Baja California. México ",
                            Name = "COLONIA LOMAS DEL PORVENIR DE TIJUANA"
                        },
                        new
                        {
                            BranchId = 37,
                            Location = "PASEO DE ENSENADA  1845, JARDINES DEL SOL, 22504 Baja California. México ",
                            Name = "COLONIA PLAYAS DE TIJUANA"
                        },
                        new
                        {
                            BranchId = 38,
                            Location = "MÁRTIRES DE CHICAGO 2DA. SECCION S/N, OBRERA, 22625 Baja California. México ",
                            Name = "COLONIA PRIMERO DE MAYO DE TIJUANA"
                        },
                        new
                        {
                            BranchId = 40,
                            Location = "AV. OBREGÓN  658, PRIMERA SECCION, 21100 Baja California. México ",
                            Name = "COLONIA NUEVA DE MEXICALI"
                        },
                        new
                        {
                            BranchId = 42,
                            Location = "CALLE HIDALGO  106, EL SAUZAL, 22760 Baja California. México ",
                            Name = "EL SAUZAL DE RODRÍGUEZ"
                        },
                        new
                        {
                            BranchId = 43,
                            Location = "CALLE FLORESTA  300, OBRERA, 22800 Baja California. México ",
                            Name = "ENSENADA"
                        },
                        new
                        {
                            BranchId = 44,
                            Location = "CALLE CUARTA  S/N, COLONIAS NUEVAS, 21800 Baja California. México ",
                            Name = "ESTACIÓN COAHUILA"
                        },
                        new
                        {
                            BranchId = 45,
                            Location = "AV. JOSEFA ORTIZ DE DOMINGUEZ  S/N, ESTACIÓN DELTA, 21700 Baja California. México ",
                            Name = "ESTACIÓN DELTA"
                        },
                        new
                        {
                            BranchId = 46,
                            Location = "CALLE QUINTA  367, GUADALUPE VICTORIA KM 43, 21720 Baja California. México ",
                            Name = "ESTACIÓN VICTORIA"
                        },
                        new
                        {
                            BranchId = 47,
                            Location = "BLVD. GRAL. VENUSTIANO CARRANZA  673, FRACCIONAMIENTO PASEOS DEL SOL, 21399 Baja California. México ",
                            Name = "GONZÁLEZ ORTEGA"
                        },
                        new
                        {
                            BranchId = 48,
                            Location = "CALLE DEL ARROYO  S/N, VISTA AL MAR, 22990 Baja California. México ",
                            Name = "ISLA DE CEDROS"
                        },
                        new
                        {
                            BranchId = 49,
                            Location = "BOULEVARD INDUSTRIAL 1100, LA MESA DE OTAY, 22436 Baja California. México ",
                            Name = "OTAY DE TIJUANA"
                        },
                        new
                        {
                            BranchId = 51,
                            Location = "AV. BENITO JUÁREZ  S/N, LUIS ECHEVERRÍA ÁLVAREZ, 21505 Baja California. México ",
                            Name = "EL HONGO"
                        },
                        new
                        {
                            BranchId = 53,
                            Location = "AV. MADERO  491, CENTRO, 21100 Baja California. México ",
                            Name = "MADERO DE MEXICALI"
                        },
                        new
                        {
                            BranchId = 54,
                            Location = "CARRETERA TRANSPENINSULAR  1400, PARTE ALTA, 22790 Baja California. México ",
                            Name = "MANEADERO"
                        },
                        new
                        {
                            BranchId = 56,
                            Location = "DERECHO DE VIA PÚBLICA C.F.E. 2091, FRACCIONAMIENTO CHULAVISTA, 22710 Baja California. México ",
                            Name = "PLAYAS DE ROSARITO"
                        },
                        new
                        {
                            BranchId = 57,
                            Location = "AV. MAR NEGRO   S/N, CENTRO SECCIÓN 2, 21850 Baja California. México ",
                            Name = "SAN FELIPE"
                        },
                        new
                        {
                            BranchId = 58,
                            Location = "PRESIDENTE PASCUAL ORTIZ RUBIO  145, ZONA CENTRO, 21430 Baja California. México ",
                            Name = "TECATE"
                        },
                        new
                        {
                            BranchId = 59,
                            Location = "AV. LÁZARO CÁRDENAS  1000, ALAMAR, 22540 Baja California. México ",
                            Name = "TERMINAL DE AUTOBUSES DE TIJUANA"
                        },
                        new
                        {
                            BranchId = 60,
                            Location = "AV.  NEGRETE  2050, CENTRO, 22000 Baja California. México ",
                            Name = "TIJUANA"
                        },
                        new
                        {
                            BranchId = 64,
                            Location = "CARRETERA MEXICALI-TIJUANA KM 69.5  S/N, CENTRO, 21510 Baja California . México ",
                            Name = "LA RUMOROSA "
                        },
                        new
                        {
                            BranchId = 65,
                            Location = "CARRETERA TECATE-ENSENADA KM 13.5  S/N, NUEVA HINDÚ SECC. CERRO AZUL, 21507 Baja California . México ",
                            Name = "COLONIA HINDÚ"
                        },
                        new
                        {
                            BranchId = 66,
                            Location = "AVE. BENITO JUÁREZ  S/N, VALLE DE LAS PALMAS , 21500 Baja California. México ",
                            Name = "VALLE DE LAS PALMAS"
                        },
                        new
                        {
                            BranchId = 68,
                            Location = "PESCADORES  S/N, CENTRO, 23960 Baja California Sur. México ",
                            Name = "BAHÍA ASUNCIÓN"
                        },
                        new
                        {
                            BranchId = 69,
                            Location = "AV BENITO JUÁREZ 52, CENTRO, 23950 Baja California Sur. México ",
                            Name = "BAHÍA TORTUGAS"
                        },
                        new
                        {
                            BranchId = 70,
                            Location = "BLVD. LÁZARO CÁRDENAS  MANZ 16, CENTRO, 23450 Baja California Sur. México ",
                            Name = "CABO SAN LUCAS"
                        },
                        new
                        {
                            BranchId = 71,
                            Location = "BENITO JUÁREZ  S/N, CENTRO, 23600 Baja California Sur. México ",
                            Name = "CIUDAD CONSTITUCIÓN"
                        },
                        new
                        {
                            BranchId = 72,
                            Location = "ANDADOR SEBASTIAN VIZCAINO   S/N, FOVISSSTE SUDCALIFORNIA, 23080 Baja California Sur. México ",
                            Name = "COLONIA FOVISSSTE DE LA PAZ"
                        },
                        new
                        {
                            BranchId = 73,
                            Location = "JALISCO  S/N, INFONAVIT, 23070 Baja California Sur. México ",
                            Name = "COLONIA INFONAVIT DE LA PAZ"
                        },
                        new
                        {
                            BranchId = 74,
                            Location = "NIÑOS HÉROES  S/N, PUEBLO NUEVO, 23670 Baja California Sur. México ",
                            Name = "COLONIA PUEBLO NUEVO DE CIUDAD CONSTITUCIÓN"
                        },
                        new
                        {
                            BranchId = 75,
                            Location = "CARRETERA TRANSPENINSULAR KM 7 , CENTRO, 23580 Baja California Sur. México ",
                            Name = "BUENAVISTA"
                        },
                        new
                        {
                            BranchId = 76,
                            Location = "MORELOS MANZ 173, INFONAVIT SALINEROS, 23940 Baja California Sur. México ",
                            Name = "GUERRERO NEGRO"
                        },
                        new
                        {
                            BranchId = 77,
                            Location = "ALFREDO V. BONFIL  7 LOTE 7 MANZ E , CENTRO, 23938 Baja California Sur. México ",
                            Name = "VILLA ALBERTO ANDRÉS ALVARADO ARÁMBURU"
                        },
                        new
                        {
                            BranchId = 78,
                            Location = "CONSTITUCIÓN ALTOS , CENTRO, 23000 Baja California Sur. México ",
                            Name = "LA PAZ"
                        },
                        new
                        {
                            BranchId = 79,
                            Location = "GUILLERMO PRIETO S/N, SANTA ROSA, 23428 Baja California Sur. México ",
                            Name = "SANTA ROSA"
                        },
                        new
                        {
                            BranchId = 80,
                            Location = "DEPORTIVA  12, CENTRO, 23880 Baja California Sur. México ",
                            Name = "LORETO"
                        },
                        new
                        {
                            BranchId = 81,
                            Location = "UNIÓN 11, CENTRO, 23520 Baja California Sur. México ",
                            Name = "MIRAFLORES"
                        },
                        new
                        {
                            BranchId = 82,
                            Location = "MOCTEZUMA 73, CENTRO, 23900 Baja California Sur. México ",
                            Name = "MULEGÉ"
                        },
                        new
                        {
                            BranchId = 83,
                            Location = "LA ALMEJA  S/N, CENTRO, 23973 Baja California Sur. México ",
                            Name = "LA BOCANA"
                        },
                        new
                        {
                            BranchId = 84,
                            Location = "PUERTO JUÁREZ  S/N, CENTRO, 23740 Baja California Sur. México ",
                            Name = "PUERTO SAN CARLOS"
                        },
                        new
                        {
                            BranchId = 85,
                            Location = "MIGUEL HIDALGO  S/N, CENTRO, 23970 Baja California Sur. México ",
                            Name = "PUNTA ABREOJOS"
                        },
                        new
                        {
                            BranchId = 86,
                            Location = "MORELOS 23, CENTRO, 23930 Baja California Sur. México ",
                            Name = "SAN IGNACIO"
                        },
                        new
                        {
                            BranchId = 87,
                            Location = "20 DE NOVIEMBRE  S/N, CENTRO, 23810 Baja California Sur. México ",
                            Name = "SAN ISIDRO"
                        },
                        new
                        {
                            BranchId = 88,
                            Location = "BLVD. MIJAREZ  MZA 60, CENTRO, 23400 Baja California Sur. México ",
                            Name = "SAN JOSÉ DEL CABO"
                        },
                        new
                        {
                            BranchId = 89,
                            Location = "PEDRO ALTAMIRANO 7, CENTRO, 23920 Baja California Sur. México ",
                            Name = "SANTA ROSALÍA"
                        },
                        new
                        {
                            BranchId = 90,
                            Location = "FRANCISCO VILLA  S/N, CHAMETLA, 23205 Baja California Sur. México ",
                            Name = "CHAMETLA "
                        },
                        new
                        {
                            BranchId = 91,
                            Location = "CENTENARIO, EDIFICIO DE LA MUNICIPALIDAD S/N, CENTRO, 23300 Baja California Sur. México ",
                            Name = "TODOS SANTOS"
                        },
                        new
                        {
                            BranchId = 92,
                            Location = "LÓPEZ MATEOS Y ALLENDE INT. EDIFICIO DELEG. MUNICIPAL  , CENTRO, 23700 Baja California Sur. México ",
                            Name = "VILLA INSURGENTES"
                        },
                        new
                        {
                            BranchId = 93,
                            Location = "GUILLERMO PRIETO  S/N, CENTRO, 23000 Baja California Sur. México ",
                            Name = "MUSEO DE LA PAZ"
                        },
                        new
                        {
                            BranchId = 94,
                            Location = "MADERO  INTERIOR DE LA SUBDELEGACIÓN S/N, CENTRO, 23200 Baja California Sur. México ",
                            Name = "SAN JUAN DE LOS PLANES"
                        },
                        new
                        {
                            BranchId = 95,
                            Location = "PADRE JAIME BRAVO  S/N, LIENZO CHARRO, 23030 Baja California Sur. México ",
                            Name = "COL. LIENZO CHARRO DE LA PAZ"
                        },
                        new
                        {
                            BranchId = 96,
                            Location = "VICENTE GUERRERO  98, CENTRO, 24326 Campeche. México ",
                            Name = "ATASTA"
                        },
                        new
                        {
                            BranchId = 97,
                            Location = "CALLE 33  193, CENTRO, 24930 Campeche. México ",
                            Name = "BECAL"
                        },
                        new
                        {
                            BranchId = 98,
                            Location = "CALLE 10  S/N, CENTRO, 24620 Campeche. México ",
                            Name = "BOLONCHÉN DE REJÓN"
                        },
                        new
                        {
                            BranchId = 99,
                            Location = "CALLE 20 129, CENTRO, 24900 Campeche. México ",
                            Name = "CALKINI"
                        },
                        new
                        {
                            BranchId = 100,
                            Location = "AVENIDA 16 DE DE SEPTIEMBRE, PALACIO FEDERAL PLANTA BAJA S/N, CENTRO, 24000 Campeche. México ",
                            Name = "CAMPECHE"
                        },
                        new
                        {
                            BranchId = 101,
                            Location = "CALLE 18  8, CENTRO, 24330 Campeche. México ",
                            Name = "CANDELARIA"
                        },
                        new
                        {
                            BranchId = 102,
                            Location = "CALLE 20  208, CENTRO, 24100 Campeche. México ",
                            Name = "CIUDAD DEL CARMEN"
                        },
                        new
                        {
                            BranchId = 103,
                            Location = "CALLE 32  4, CENTRO, 24400 Campeche. México ",
                            Name = "CHAMPOTON"
                        },
                        new
                        {
                            BranchId = 104,
                            Location = "CALLE 30 BAJOS PALACIO MUNICIPAL S/N, CENTRO, 24611 Campeche. México ",
                            Name = "DZIBALCHEN"
                        },
                        new
                        {
                            BranchId = 105,
                            Location = "CARRETERA FEDERAL KM. 70 S/N, CENTRO, 24658 Campeche. México ",
                            Name = "CONSTITUCIÓN"
                        },
                        new
                        {
                            BranchId = 106,
                            Location = "CALLE 31-B  S/N, CENTRO, 24350 Campeche. México ",
                            Name = "ESCARCEGA"
                        },
                        new
                        {
                            BranchId = 107,
                            Location = "CALLE 20 EDIFICIO FEDERAL S/N, CENTRO, 24800 Campeche. México ",
                            Name = "HECELCHAKAN"
                        },
                        new
                        {
                            BranchId = 108,
                            Location = "CALLE 19  74, CENTRO, 24600 Campeche. México ",
                            Name = "HOPELCHEN"
                        },
                        new
                        {
                            BranchId = 109,
                            Location = "AV. 20 DE NOVIEMBRE  S/N, CENTRO, 24314 Campeche. México ",
                            Name = "MAMANTEL"
                        },
                        new
                        {
                            BranchId = 110,
                            Location = "CALLE MARINA  23, ISLA AGUADA CENTRO, 24327 Campeche. México ",
                            Name = "ISLA AGUADA"
                        },
                        new
                        {
                            BranchId = 111,
                            Location = "CALLE 10  EDIFICIO CASA DE LA CULTURA S/N, CENTRO, 24700 Campeche. México ",
                            Name = "TENABO"
                        },
                        new
                        {
                            BranchId = 112,
                            Location = "MIGUEL HIDALGO  EDIFICIO DIF 30, CENTRO, 24200 Campeche. México ",
                            Name = "PALIZADA "
                        },
                        new
                        {
                            BranchId = 113,
                            Location = "CALLE 22  S/N, CENTRO, 24570 Campeche. México ",
                            Name = "ALFREDO V. BONFIL"
                        },
                        new
                        {
                            BranchId = 114,
                            Location = "MANUEL J. LÓPEZ  HERNÁNDEZ  2, CENTRO, 24300 Campeche. México ",
                            Name = "SABANCUY"
                        },
                        new
                        {
                            BranchId = 115,
                            Location = "CALLE 23, BAJOS DEL PALACIO MUNICIPAL S/N, CENTRO, 24460 Campeche. México ",
                            Name = "SEYBAPLAYA"
                        },
                        new
                        {
                            BranchId = 116,
                            Location = "CALLE 2 S/N, JARDINES, 24640 Campeche. México ",
                            Name = "XPUJIL"
                        },
                        new
                        {
                            BranchId = 117,
                            Location = "AV. CONCORDIA 90, AMPLIACIÓN ESPERANZA, 24085 Campeche. México ",
                            Name = "COLONIA CIUDAD CONCORDIA"
                        },
                        new
                        {
                            BranchId = 118,
                            Location = "CARMEN SUR S/N, EL AGUACATAL CENTRO , 24317 Campeche. México ",
                            Name = "AGUACATAL"
                        },
                        new
                        {
                            BranchId = 119,
                            Location = "ERMITA  S/N, SIHOCHAC CENTRO, 24450 Campeche. México ",
                            Name = "SIHOCHAC"
                        },
                        new
                        {
                            BranchId = 121,
                            Location = "CALLE 14  S/N, CENTRO POMUCH, 24810 Campeche. México ",
                            Name = "POMUCH"
                        },
                        new
                        {
                            BranchId = 122,
                            Location = "CALLE 25 BAJOS DEL PALACIO EJIDAL S/N, DZITBALCHÉ CENTRO, 24920 Campeche. México ",
                            Name = "DZITBALCHÉ"
                        },
                        new
                        {
                            BranchId = 123,
                            Location = "VERACRUZ  202, SANTA ANA, 24050 Campeche. México ",
                            Name = "COLONIA LOMAS "
                        },
                        new
                        {
                            BranchId = 124,
                            Location = "CARRETERA FEDERAL CHAMPOTÓN-ESCARCEGA K.M. 38, XBACAB CENTRO, 24416 Campeche. México ",
                            Name = "XBACAB"
                        },
                        new
                        {
                            BranchId = 125,
                            Location = "LIC. RAÚL LÓPEZ SÁNCHEZ  7, CENTRO, 26640 Coahuila de Zaragoza. México ",
                            Name = "GUERRERO   "
                        },
                        new
                        {
                            BranchId = 126,
                            Location = "HIDALGO 2, CENTRO, 25350 Coahuila de Zaragoza. México ",
                            Name = "ARTEAGA"
                        },
                        new
                        {
                            BranchId = 127,
                            Location = "MIGUEL HIDALGO  407, CENTRO, 25570 Coahuila de Zaragoza. México ",
                            Name = "CANDELA"
                        },
                        new
                        {
                            BranchId = 128,
                            Location = "HIDALGO  100, CENTRO, 25870 Coahuila de Zaragoza. México ",
                            Name = "CASTAÑOS"
                        },
                        new
                        {
                            BranchId = 129,
                            Location = "HIDALGO  39, NADADORES CENTRO , 27550 Coahuila de Zaragoza. México ",
                            Name = "NADADORES "
                        },
                        new
                        {
                            BranchId = 130,
                            Location = "GUERRERO  535, CENTRO, 26200 Coahuila de Zaragoza. México ",
                            Name = "CIUDAD ACUÑA"
                        },
                        new
                        {
                            BranchId = 131,
                            Location = "GUERRERO SUR 506, CENTRO, 26530 Coahuila de Zaragoza. México ",
                            Name = "CIUDAD ALLENDE"
                        },
                        new
                        {
                            BranchId = 132,
                            Location = "PRESIDENTE CARRANZA  SUR 101,  CENTRO, 25600 Coahuila de Zaragoza. México ",
                            Name = "CIUDAD FRONTERA"
                        },
                        new
                        {
                            BranchId = 133,
                            Location = "5 DE MAYO  110-A OTE, CENTRO, 26340 Coahuila de Zaragoza. México ",
                            Name = "CIUDAD MELCHOR MUZQUIZ"
                        },
                        new
                        {
                            BranchId = 134,
                            Location = "FCO I MADERO  152, CENTRO, 26700 Coahuila de Zaragoza. México ",
                            Name = "CIUDAD SABINAS"
                        },
                        new
                        {
                            BranchId = 136,
                            Location = "BELISARIO DOMÍNGUEZ   650, BENITO JUÁREZ, 26215 Coahuila de Zaragoza. México ",
                            Name = "COLONIA BENITO JUÁREZ DE CIUDAD ACUÑA"
                        },
                        new
                        {
                            BranchId = 137,
                            Location = "AVENIDA PERIODISTAS 712, LAS FUENTES, 26010 Coahuila de Zaragoza. México ",
                            Name = "AVENIDA PERIODISTAS DE PIEDRAS NEGRAS"
                        },
                        new
                        {
                            BranchId = 138,
                            Location = "SECUNDARIA #1 744, OBRERA SUR, 25790 Coahuila de Zaragoza. México ",
                            Name = "COLONIA OBRERA SUR DE MONCLOVA"
                        },
                        new
                        {
                            BranchId = 139,
                            Location = "BLVD FCO COSS, SORIANA , CENTRO , 25000 Coahuila de Zaragoza. México ",
                            Name = "COLONIA REPÚBLICA NORTE DE SALTILLO"
                        },
                        new
                        {
                            BranchId = 140,
                            Location = "MELCHOR OCAMPO  105, CUATROCIÉNEGAS DE CARRANZA CENTRO , 27640 Coahuila de Zaragoza. México ",
                            Name = "CUATROCIÉNEGAS DE CARRANZA"
                        },
                        new
                        {
                            BranchId = 141,
                            Location = "AVENIDA LOPEZ MATEOS 318, NUEVO LINARES DEL SUR, 27900 Coahuila de Zaragoza. México ",
                            Name = "FRANCISCO I.  MADERO"
                        },
                        new
                        {
                            BranchId = 142,
                            Location = "HIDALGO  S/N, CENTRO, 25950 Coahuila de Zaragoza. México ",
                            Name = "GENERAL CEPEDA"
                        },
                        new
                        {
                            BranchId = 143,
                            Location = "BLVD. FRANCISCO COSS  1102, CENTRO, 25000 Coahuila de Zaragoza. México ",
                            Name = "GENERAL COSS DE SALTILLO"
                        },
                        new
                        {
                            BranchId = 144,
                            Location = "MORELOS  44, CENTRO, 27750 Coahuila de Zaragoza. México ",
                            Name = "SACRAMENTO"
                        },
                        new
                        {
                            BranchId = 145,
                            Location = "VENUSTIANO CARRANZA S/N, CENTRO, 27610 Coahuila de Zaragoza. México ",
                            Name = "LA ESMERALDA"
                        },
                        new
                        {
                            BranchId = 146,
                            Location = "LA NEGRA  108, COL IINDUSTRIAL, 27545 Coahuila de Zaragoza. México ",
                            Name = "LAGUNA DEL REY"
                        },
                        new
                        {
                            BranchId = 147,
                            Location = "BLVD CONSTITUCIÓN (SORIANA) 1111, AMPLIACIÓN LAS MARGARITAS , 27130 Coahuila de Zaragoza. México ",
                            Name = "BOULEVARD CONSTITUCIÓN DE TORREÓN"
                        },
                        new
                        {
                            BranchId = 148,
                            Location = "LIBERTAD  110 BIS , MATAMOROS DE LA LAGUNA CENTRO, 27440 Coahuila de Zaragoza. México ",
                            Name = "MATAMOROS DE LA LAGUNA"
                        },
                        new
                        {
                            BranchId = 149,
                            Location = "BLVD. MUZQUIZ, EDIFICIO COMISARIA  S/N, CENTRO, 26370 Coahuila de Zaragoza. México ",
                            Name = "MINAS DE BARROTERAN"
                        },
                        new
                        {
                            BranchId = 150,
                            Location = " DE LA FUENTE  103 NTE, CENTRO, 25700 Coahuila de Zaragoza. México ",
                            Name = "MONCLOVA"
                        },
                        new
                        {
                            BranchId = 151,
                            Location = "JUÁREZ   308, CENTRO, 26500 Coahuila de Zaragoza. México ",
                            Name = "MORELOS"
                        },
                        new
                        {
                            BranchId = 152,
                            Location = "ZARAGOZA, INTERIOR DE LA PRESIDENCIA MUNICIPAL S/N, CENTRO, 26170 Coahuila de Zaragoza. México ",
                            Name = "NAVA"
                        },
                        new
                        {
                            BranchId = 153,
                            Location = "BLVD. INDEPENDENCIA, IPERMART INDEPENDENCIA 1100, CENTRO, 27000 Coahuila de Zaragoza. México ",
                            Name = "NIÑOS HEROES DE TORREÓN"
                        },
                        new
                        {
                            BranchId = 154,
                            Location = "AVENIDA LÓPEZ MATEOS  S/N, CENTRO, 26800 Coahuila de Zaragoza. México ",
                            Name = "NUEVA ROSITA"
                        },
                        new
                        {
                            BranchId = 155,
                            Location = "VENUSTIANO CARRANZA  05 OTE, CENTRO, 26350 Coahuila de Zaragoza. México ",
                            Name = "PALAU"
                        },
                        new
                        {
                            BranchId = 156,
                            Location = "LIC. ARNULFO R. GARCIA  S/N, CENTRO, 25910 Coahuila de Zaragoza. México ",
                            Name = "PAREDÓN"
                        },
                        new
                        {
                            BranchId = 157,
                            Location = "RAMOS ARÍZPE 123, CENTRO, 27980 Coahuila de Zaragoza. México ",
                            Name = "PARRAS DE LA FUENTE"
                        },
                        new
                        {
                            BranchId = 158,
                            Location = "DE LA FUENTE OTE. Y MORELOS  S/N, CENTRO, 26000 Coahuila de Zaragoza. México ",
                            Name = "PIEDRAS NEGRAS"
                        },
                        new
                        {
                            BranchId = 159,
                            Location = "JOSÉ A. VILLARREAL 203, CENTRO, 25900 Coahuila de Zaragoza. México ",
                            Name = "RAMOS ARÍZPE"
                        },
                        new
                        {
                            BranchId = 160,
                            Location = "GUADALUPE VICTORIA  289 PTE, CENTRO, 25000 Coahuila de Zaragoza. México ",
                            Name = "SALTILLO"
                        },
                        new
                        {
                            BranchId = 161,
                            Location = "FRANCISCO I MADERO  264, CENTRO, 25500 Coahuila de Zaragoza. México ",
                            Name = "SAN BUENAVENTURA"
                        },
                        new
                        {
                            BranchId = 162,
                            Location = " LERDO  11 OTE, CENTRO, 27800 Coahuila de Zaragoza. México ",
                            Name = "SAN PEDRO DE LAS COLONIAS"
                        },
                        new
                        {
                            BranchId = 163,
                            Location = "BLVD. JUÁREZ  6, EL PUEBLO, 25730 Coahuila de Zaragoza. México ",
                            Name = "SECTOR EL PUEBLO DE MONCLOVA, COAHUILA"
                        },
                        new
                        {
                            BranchId = 164,
                            Location = "AV. JUÁREZ, INTERIOR 3 DEL PALACIO FEDERAL  S/N, CENTRO, 27000 Coahuila de Zaragoza. México ",
                            Name = "TORREÓN"
                        },
                        new
                        {
                            BranchId = 166,
                            Location = "AV. 5 DE MAYO  14, CENTRO, 27480 Coahuila de Zaragoza. México ",
                            Name = "VIESCA"
                        },
                        new
                        {
                            BranchId = 167,
                            Location = "CALLE HIDALGO 101 SUR , VILLA DE FUENTE, 26090 Coahuila de Zaragoza. México ",
                            Name = "VILLA DE FUENTE"
                        },
                        new
                        {
                            BranchId = 168,
                            Location = "ZARAGOZA 211, CENTRO, 27500 Coahuila de Zaragoza. México ",
                            Name = "VILLA OCAMPO"
                        },
                        new
                        {
                            BranchId = 170,
                            Location = "ALLENDE  106, CENTRO, 26450 Coahuila de Zaragoza. México ",
                            Name = "ZARAGOZA"
                        },
                        new
                        {
                            BranchId = 172,
                            Location = "DOMICILIO CONOCIDO , EJIDO LUCHANA, 27940 Coahuila de Zaragoza. México ",
                            Name = "LUCHANA"
                        },
                        new
                        {
                            BranchId = 174,
                            Location = "CALLE PRINCIPAL  S/N, CENTRO, 27450 Coahuila de Zaragoza. México ",
                            Name = "EJIDO EL COYOTE"
                        },
                        new
                        {
                            BranchId = 175,
                            Location = "AVENIDA MORELOS 765 PTE, CENTRO, 27000 Coahuila de Zaragoza. México ",
                            Name = "AVENIDA MORELOS DE TORREÓN"
                        },
                        new
                        {
                            BranchId = 176,
                            Location = "POSEIDÓN  S/N, CENTRO, 27603 Coahuila de Zaragoza. México ",
                            Name = "HÉRCULES"
                        },
                        new
                        {
                            BranchId = 178,
                            Location = "VENUSTIANO CARRANZA  4, SANTIAGO, 28860 Colima. México ",
                            Name = "ABELARDO L. RODRÍGUEZ "
                        },
                        new
                        {
                            BranchId = 179,
                            Location = "CHIHUAHUA  3, CENTRO, 28300 Colima. México ",
                            Name = "ARMERIA "
                        },
                        new
                        {
                            BranchId = 180,
                            Location = "AV. REVOLUCIÓN  PALACIO MUNICIPAL S/N, CENTRO, 28900 Colima. México ",
                            Name = "CERRO DE ORTEGA"
                        },
                        new
                        {
                            BranchId = 181,
                            Location = "ALLENDE 30, CENTRO, 28350 Colima. México ",
                            Name = "COFRADIA DE JUÁREZ "
                        },
                        new
                        {
                            BranchId = 182,
                            Location = "FRANCISCO I. MADERO  243, CENTRO, 28000 Colima. México ",
                            Name = "COLIMA"
                        },
                        new
                        {
                            BranchId = 183,
                            Location = "AND PLAYA LA AUDIENCIA 310, LAS BRISAS, 28210 Colima. México ",
                            Name = "COLONIA LAS BRISAS DE MANZANILLO "
                        },
                        new
                        {
                            BranchId = 184,
                            Location = "GUILLERMO PRIETO  100 N, CENTRO, 28450 Colima. México ",
                            Name = "COMALA"
                        },
                        new
                        {
                            BranchId = 185,
                            Location = "BENITO JUÁREZ  349, CENTRO, 28400 Colima. México ",
                            Name = "COQUIMATLAN"
                        },
                        new
                        {
                            BranchId = 186,
                            Location = "MIGUEL HIDALGO, INTERIOR H. AYUNTAMIENTO  5, CENTRO, 28500 Colima. México ",
                            Name = "CUAUHTÉMOC"
                        },
                        new
                        {
                            BranchId = 187,
                            Location = "LA PAZ  12, CENTRO, 28350 Colima. México ",
                            Name = "CUYUTLAN"
                        },
                        new
                        {
                            BranchId = 188,
                            Location = "VENUSTIANO CARRANZA S/N, CENTRO, 28800 Colima. México ",
                            Name = "EL COLOMO"
                        },
                        new
                        {
                            BranchId = 189,
                            Location = "CALLE MORELOS, INTERIOR H. AYUNTAMIENTO  1, CENTRO, 28700 Colima. México ",
                            Name = "IXTLAHUACAN"
                        },
                        new
                        {
                            BranchId = 190,
                            Location = "CARRILLO PUERTO 135, CENTRO, 28200 Colima. México ",
                            Name = "MANZANILLO"
                        },
                        new
                        {
                            BranchId = 191,
                            Location = "FRANCISCO I. MADERO 38-A, CENTRO, 28600 Colima. México ",
                            Name = "LOS TEPAMES"
                        },
                        new
                        {
                            BranchId = 192,
                            Location = "INDEPENDENCIA  27, CENTRO, 28750 Colima. México ",
                            Name = "MINATITLÁN"
                        },
                        new
                        {
                            BranchId = 193,
                            Location = "MOCTEZUMA   1-D, CENTRO, 28510 Colima. México ",
                            Name = "QUESERÍA"
                        },
                        new
                        {
                            BranchId = 194,
                            Location = "ALDAMA 230, CENTRO, 28100 Colima. México ",
                            Name = "TECOMÁN"
                        },
                        new
                        {
                            BranchId = 195,
                            Location = "ARGENTINA, PRESIDENCIA MUNICIPAL 109, CENTRO, 28910 Colima. México ",
                            Name = "MADRID"
                        },
                        new
                        {
                            BranchId = 196,
                            Location = "AV. J. MERCED CABRERA  84, CENTRO, 28950 Colima. México ",
                            Name = "VILLA DE ÁLVAREZ "
                        },
                        new
                        {
                            BranchId = 197,
                            Location = "AV. PRIMAVERA  MZ 53, VALLE DE LAS GARZAS BARRIO II, 28219 Colima. México ",
                            Name = "COLONIA VALLE DE LAS GARZAS "
                        },
                        new
                        {
                            BranchId = 198,
                            Location = "AV. INSURGENTES, P.B. 680, CAMINO REAL, 28040 Colima. México ",
                            Name = "COLONIA CAMINO REAL DE COLIMA "
                        },
                        new
                        {
                            BranchId = 199,
                            Location = "AV. NIÑOS HÉROES 353 P.B., JUAN JOSÉ RÍOS II, 28984 Colima. México ",
                            Name = "JUAN JOSÉ RÍOS "
                        },
                        new
                        {
                            BranchId = 200,
                            Location = "MIRTO 4, SUCHITLÁN CENTRO, 28459 Colima. México ",
                            Name = "SUCHITLÁN"
                        },
                        new
                        {
                            BranchId = 201,
                            Location = "AV. CENTRAL  BAJOS PALACIO MUNICIPAL. S/N, CENTRO, 30580 Chiapas. México ",
                            Name = "ACAPETAHUA"
                        },
                        new
                        {
                            BranchId = 202,
                            Location = "CALLE CENTRAL 5, AMATÁN CENTRO, 29700 Chiapas. México ",
                            Name = "AMATÁN"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
